### ISSUE TITLE
[Bug]: "ERROR: python3-venv is not installed" when installing on external drive

### ISSUE THREAD

**Issue by marcomastri** [brkirch/stable-diffusion-webui#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I get this error both when installing on an external hard drive, and when installing on the Macbook then moving the directory the external drive.

### Steps to reproduce the problem

1. Run the installer
2. Choose an external drive as the install location
3. Run the "Launch Web UI" app

### What should have happened?

I have no problem running vanilla stable-diffusion-webui from an external HD.

### Commit where the problem happens

20230416

### What platforms do you use to access the UI ?

MacOS

### Command Line Arguments

```Shell
No
```

### List of extensions

No

### Console logs

```Shell
################################################################
                          **WARNING**
  This is a test build of stable-diffusion-webui and PyTorch!
Crashes and bugs are expected, do not assume it will be stable!
   DO NOT report issues to the web UI or PyTorch developers!
Report issues to github.com/brkirch/stable-diffusion-webui/issues
################################################################

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on ****** user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
ERROR: python3-venv is not installed, aborting...
################################################################
logout

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Processo completato]
```

**Comment by semse** [comment]
same issue. Anyone know how to resolve?

**Comment by a-starry-night** [comment]
same issue here, tried several tipps from here but those didn't resolve it for me
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/1120

**Comment by brkirch** [comment]
This should be fixed in [20230913_experimental](https://github.com/brkirch/stable-diffusion-webui/releases/tag/20230913_experimental), please let me know if there are any further issues.

**Comment by a-starry-night** [comment]
didnt try the fixes above again but on its own, it still throws the same error (tested with linked version, installer)
